---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: ml
  annotations:
    serving.kserve.io/s3-endpoint: s3.amazonaws.com
    serving.kserve.io/s3-usehttps: "1"
    serving.kserve.io/s3-region: eu-north-1
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "AKIA3P2U3264N4I36KEJ"
  AWS_SECRET_ACCESS_KEY: "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"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-s3-access
  namespace: ml
  secrets:
  - name: s3-secret
